export {
	MobileButton,
	MobileInput as Input,
	MobileMotionButton,
	MobileMotionInput as MotionInput,
	MobileMotionSelect as MotionSelect,
	MobileMotionTabs as MotionTabs,
	MobileMotionTabsContent as MotionTabsContent,
	MobileMotionTabsList as MotionTabsList,
	MobileMotionTabsTrigger as MotionTabsTrigger,
	MobileNotTypeset,
	MobileSelect as Select,
	MobileStatefulButton as StatefulButton,
	MobileTabs as Tabs,
	MobileTabsContent as TabsContent,
	MobileTabsList as TabsList,
	MobileTabsTrigger as TabsTrigger,
	MobileTypeset,
	MobileTypesetBlockquote,
	MobileTypesetCode,
	MobileTypesetHeading,
	MobileTypesetParagraph,
	MobileTypesetScroll,
	useMobileTypeset,
} from "@school-os/ui/components/mobile";
